    {
        "adapters": 1,
        "builtin": false,
        "category": "guest",
        "compute_id": "local",
        "console_auto_start": false,
        "console_http_path": "/",
        "console_http_port": 80,
        "console_resolution": "1024x768",
        "console_type": "telnet",
        "custom_adapters": [],
        "default_name_format": "{name}-{0}",
        "environment": "",
        "extra_hosts": "",
        "extra_volumes": [],
        "image": "registry.cri.epita.fr/daniel.stan/net2-appliances/net2-pebble",
        "name": "net2-pebble",
        "start_command": "",
        "symbol": "letsencrypt-logo.png",
        "template_id": "fd6d2c35-9eb4-4967-9330-8c2080c5baeb",
        "template_type": "docker",
        "usage": ""
    }
