    {
        "adapters": 1,
        "builtin": false,
        "category": "guest",
        "compute_id": "local",
        "console_auto_start": false,
        "console_http_path": "/",
        "console_http_port": 80,
        "console_resolution": "1024x768",
        "console_type": "telnet",
        "custom_adapters": [],
        "default_name_format": "{name}-{0}",
        "environment": "",
        "extra_hosts": "",
        "extra_volumes": [],
        "image": "registry.cri.epita.fr/daniel.stan/net2-appliances/net2-webserver",
        "name": "net2-webserver",
        "start_command": "",
        "symbol": "webserver.svg",
        "template_id": "7da431cf-aba4-4d8c-8a5b-ed9f152b7a25",
        "template_type": "docker",
        "usage": ""
    }
